### ISSUE TITLE
Link no Github Pages

### ISSUE THREAD

**Issue by benmacario** [sinetoami/covid19news#1]
Seu link no GitHub Pages está desatualizado, creio eu. Não está sendo possível acessá-lo, acho que pelo motivo de ter mudado o nome do repositório de *covid19news* para *gama-covid19news*.

**Comment by sineto** [comment]
Atualizado. 

Boa observação, @benmacario. Na realidade eu troquei de host e owner e acabei esquecendo de atualizar o link. Obrigado!
